//! Embed the Windows application icon into the seed-gui exe so it shows in
//! Explorer, the taskbar, and the window. The icon lives at the repo root
//! (icon/appIcon.ico), i.e. two levels up from this crate. It is a
//! multi-resolution .ico (16/32/48/64/128/256) generated by
//! scripts/generate-icons.py from the img/ source art.
//!
//! No-op on non-Windows hosts (the Linux/macOS builds don't carry it).

fn main() {
    println!("cargo:rerun-if-changed=../../icon/appIcon.ico");
    #[cfg(windows)]
    {
        let mut res = winresource::WindowsResource::new();

        // Cross-compiling to ARM64 (aarch64-pc-windows-gnullvm, the target the MSYS2
        // GTK stack forces on us): winresource deliberately passes no `--target` to
        // windres for aarch64, so an unprefixed windres happily emits an *x64* object
        // and the link then dies with "machine type x64 conflicts with arm64". The
        // aarch64-prefixed driver from llvm-mingw infers the right target from its own
        // name. Host builds are unaffected — this only fires when the TARGET is aarch64.
        let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
        let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
        if target_arch == "aarch64" && target_env == "gnu" {
            res.set_windres_path("aarch64-w64-mingw32-windres");
        }

        res.set_icon("../../icon/appIcon.ico");
        if let Err(e) = res.compile() {
            // Don't fail the build if the resource compiler is unavailable; just
            // ship without the embedded icon and make it visible.
            println!("cargo:warning=failed to embed app icon: {e}");
        }
    }
}
