//! Embed the Windows application icon into the seed-gui exe so it shows in
//! Explorer, the taskbar, and the window. The icon lives at the repo root
//! (icon/appIcon.ico), i.e. two levels up from this crate. It is a
//! multi-resolution .ico (16/32/48/64/128/256) generated by
//! scripts/generate-icons.py from the img/ source art.
//!
//! No-op on non-Windows hosts (the Linux/macOS builds don't carry it).

fn main() {
    println!("cargo:rerun-if-changed=../../icon/appIcon.ico");
    #[cfg(windows)]
    {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("../../icon/appIcon.ico");
        if let Err(e) = res.compile() {
            // Don't fail the build if the resource compiler is unavailable; just
            // ship without the embedded icon and make it visible.
            println!("cargo:warning=failed to embed app icon: {e}");
        }
    }
}
